<a href="https://colab.research.google.com/github/Behruz-A/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd



print(pd.__version__)

2.2.3

In [14]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "BMW"],
    'counts': [3, 7, 2, 8, 9, 0]
}

df = pd.DataFrame(mydataset)
print(myvar)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       9
5      BMW       0
      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       9
5      BMW       0

In [15]:
df.head() #default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       9

In [18]:
df.tail() # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       9
5      BMW       0

In [21]:
df.shape

(6, 2)

In [25]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [33]:
df.dtypes
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       9
5      BMW       0

In [34]:
df.describe(include="all") # numerical columns only

       cars    counts
count     6  6.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.833333
std     NaN  3.656045
min     NaN  0.000000
25%     NaN  2.250000
50%     NaN  5.000000
75%     NaN  7.750000
max     NaN  9.000000

In [37]:
df.iloc[2] # it uses integer postion

cars      Ford
counts       2
Name: 2, dtype: object

In [41]:
df.loc[:, "counts"] # locdan foydalanib column namelarni ishaltib keraklai column malumotlarini olib kelamiz

0    3
1    7
2    2
3    8
4    9
5    0
Name: counts, dtype: int64

In [44]:
df[df["counts"] <3]

   cars  counts
2  Ford       2
5   BMW       0

In [46]:
# df.mean(numeric_only=True)
df["counts"].mean()

df.sum()

cars      BMWVolvoFordTeslaFerrariBMW
counts                             29
dtype: object

In [48]:
df.min()

cars      BMW
counts      0
dtype: object

In [50]:
df.max()

cars      Volvo
counts        9
dtype: object

In [54]:
df.median(numeric_only=True)

counts    5.0
dtype: float64

In [56]:
df.count()

cars      6
counts    6
dtype: int64

In [59]:
df.std(numeric_only=True)

counts    3.656045
dtype: float64

In [66]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrai", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

     cars  counts
0     BMW     3.0
1   Volvo     7.0
2    None     NaN
3   Tesla     8.0
4  Ferrai     1.0
5    None     9.0
6    Ford     NaN

In [72]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [73]:
df_missing.dropna()

     cars  counts
0     BMW     3.0
1   Volvo     7.0
3   Tesla     8.0
4  Ferrai     1.0

In [75]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4   Ferrai     1.0
5  unknown     9.0
6     Ford     0.0

In [76]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [87]:
#df = pd.read_csv("Titanic-Dataset.csv")


df = pd.read_excel("test.xlsx")
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [88]:
df.to_excel("test.xlsx")

In [90]:
# Series => 10
cars = pd.Series(["BMW", "Tesla", "Ferrai"])
print(cars)

0       BMW
1     Tesla
2    Ferrai
dtype: object

In [91]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrai', None, 'Ford']