<a href="https://colab.research.google.com/github/Behruz-A/ai_foundation/blob/main/student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("student_performance.csv")

print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist())

print(df.head())

print("Summary statistics:")
print(df.describe)

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (1000000, 6)
Column name: ['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade']
   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6
1           2                     14.0                   80.0
2           3                     19.5                   86.3
3           4                     25.7                   70.2
4           5                     13.4                   81.9

   class_participation  total_score grade
0                  3.8         97.9     A
1                  2.5         83.9     B
2                  5.3        100.0     A
3                  7.0        100.0     A
4                  6.9         92.0     A
Summary statistics:
<bound method NDFrame.describe of         student_id  weekly_self_study_hours  attendance_percentage  \
0                1                     18.5                   95.6
1                2                     14.0                   80.0
2                3                     19.5                   86.3
3                4                     25.7                   70.2
4                5                     13.4                   81.9
...            ...                      ...                    ...
999995      999996                     18.0                   95.5
999996      999997                     15.7                   82.7
999997      999998                     14.2                   85.1
999998      999999                     25.3                   90.0
999999     1000000                     18.3                   84.6

        class_participation  total_score grade
0                       3.8         97.9     A
1                       2.5         83.9     B
2                       5.3        100.0     A
3                       7.0        100.0     A
4                       6.9         92.0     A
...                     ...          ...   ...
999995                  4.8        100.0     A
999996                  6.7         88.3     A
999997                  5.8         87.9     A
999998                  5.3        100.0     A
999999                  4.1        100.0     A

[1000000 rows x 6 columns]>
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB
None

In [7]:
import pandas as pd
df = pd.read_csv("student_performance.csv")
print("Average score by columns:")
df[["total_score", "weekly_self_study_hours"]].mean()

Average score by columns:

total_score                84.283845
weekly_self_study_hours    15.029127
dtype: float64

In [9]:
print("Maxumum scores by participation")
df[["class_participation", "attendance_percentage"]].min()

Maxumum scores by participation

class_participation       0.0
attendance_percentage    50.0
dtype: float64

In [11]:
# Correlation
print("Correlation:")
df[["class_participation", "attendance_percentage"]].corr()

Correlation:

                       class_participation  attendance_percentage
class_participation               1.000000              -0.000043
attendance_percentage            -0.000043               1.000000

In [20]:
import numpy as np
df["total score"] = df[["class_participation", "attendance_percentage"]].sum(axis=1)
df["average score"] = df["total score"] / 2
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0         99.4          49.70     No
1         82.5          41.25     No
2         91.6          45.80     No
3         77.2          38.60     No
4         88.8          44.40     No

In [31]:
grade_group = df.groupby("grade")[["class_participation", "weekly_self_study_hours", "attendance_percentage"]].mean()
print("student score by test preperation course:")
print(grade_group)
print(df.columns.tolist())


# Gender based average
grade = df.groupby("grade")[["class_participation", "weekly_self_study_hours", "attendance_percentage"]].mean()
print("Average score by gender:")
print(grade)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", pass_rate)

student score by test preperation course:
       class_participation  weekly_self_study_hours  attendance_percentage
grade
A                 5.986642                19.375738              84.710114
B                 5.985690                12.115533              84.696178
C                 5.976975                 7.691161              84.726340
D                 5.991766                 3.764143              84.723243
F                 5.978337                 1.524662              84.973662
['student_id', 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score', 'grade', 'total score', 'average score', 'passed']
Average score by gender:
       class_participation  weekly_self_study_hours  attendance_percentage
grade
A                 5.986642                19.375738              84.710114
B                 5.985690                12.115533              84.696178
C                 5.976975                 7.691161              84.726340
D                 5.991766                 3.764143              84.723243
F                 5.978337                 1.524662              84.973662
Pass rate:
 passed
No     81.0461
Yes    18.9539
Name: proportion, dtype: float64

In [36]:
# Convert scores to Numpy array
scores = df[["class_participation", "weekly_self_study_hours", "attendance_percentage"]].values

# Mean, Std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (normalized numbers)")
print(z_score[:5])

# Average 0
# Negative -
# Positive +

Numpy Mean: [ 5.9852026 15.0291269 84.711046 ]
Numpy Std: [1.95641953 6.89942757 9.42413867]
Z-scores (normalized numbers)
[[-1.11693968  0.50306682  1.15543228]
 [-1.78141884 -0.1491612  -0.49989141]
 [-0.35023296  0.64800638  0.16860469]
 [ 0.51870132  1.54663166 -1.53977424]
 [ 0.46758754 -0.23612494 -0.29828148]]

In [40]:
 # How many students scored above 90 average?
 top_scorers = df[df["average score"] >= 90]
 print("Top scored student above 90:", len(top_scorers))

 # How many failed?
 failed = df[df["passed"] == "No"]
 print("Failed from exam:", len(failed))

Top scored student above 90: 0
Failed from exam: 810461